### ISSUE TITLE
Safari: Object passed in getCheckedRadio is not iterable, causing a for loop error

### ISSUE THREAD

**Issue by qtgye** [focus-trap/tabbable#632] opened 2022-04-12 10:27 UTC
## Description  
When focus-trap is activated via `.activate()` on an element containing a form with radio inputs, an error is thrown:  
  
<img width="461" alt="Screen Shot 2022-04-12 at 6 12 41 PM" src="https://user-images.githubusercontent.com/90045797/162938577-4139965c-2688-4719-a9a8-ba178323935f.png">

Upon inspecting `getCheckedRadio`, it appears that the `nodes` parameter is not iterable, although it has a `length` property:  
  
<img width="416" alt="Screen Shot 2022-04-12 at 6 12 23 PM" src="https://user-images.githubusercontent.com/90045797/162939488-0d9ecb89-300f-4c51-b896-057f51887fa9.png">  
  
<img width="679" alt="Screen Shot 2022-04-12 at 6 11 52 PM" src="https://user-images.githubusercontent.com/90045797/162939569-bb35497c-9937-455e-b99f-76bc8236d7d5.png">

## Environment:  
Safari 15.4
MacOS Monterey 12.3.1

**Comment by stefcameron** [comment] 2022-04-16 18:36
Thanks for reporting this, but I'm unable to repro it locally. Granted I have Safari 15.3 instead of 15.4, though I'd be surprised if 15.4 broke this. I used the "radio" example from focus-trap and replaced the `<fieldset>` with a `<form>` for the test:

![radio-in-form](https://user-images.githubusercontent.com/2855350/163687109-f4ff33b3-06cd-4751-b0ed-a68a5d3cebfa.gif)

I also added a test to tabbable for radios in a form instead of a fieldset, which works fine: #638

**Comment by stefcameron** [comment] 2022-04-20 23:14
Since I can't reproduce it, I'm going to close this issue now. Feel free to re-open it if you can show me how to reproduce it.

**Closed by stefcameron** 2022-04-20 23:14 UTC
